name: Semgrep Scan

on:
  pull_request:
    branches: [main, development]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    env:
      # this is the token stored in Settings → Secrets as SEMGREP_APP_TOKEN
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep scan
        run: semgrep ci --metrics=off --no-suppress-errors
